spring.application.name=pricing

# DATABASE CONFIG
spring.datasource.url=jdbc:postgresql://ep-plain-credit-a1ofyu9f-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&currentSchema=price2
spring.datasource.username=neondb_owner
spring.datasource.password=npg_8DwMmhLjB9TG

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=price

spring.sql.init.mode=always



server.error.include-stacktrace=never
server.error.include-message=always
server.error.include-binding-errors=never
server.error.include-exception=false



# If running locally and your Cart service is on port 8081:
cart.service.url=http://localhost:8080

# Ensure Feign is enabled and logging is useful for debugging
logging.level.io.github.openfeign=DEBUG

app.cors.allowed-origins="http://localhost:8081,http://localhost:8082,http://localhost:3000,http://localhost:3001,https://app.jjrorganics.com,https://backend.jjrorganics.com,https://admin.jjrorganics.com"
app.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
app.cors.allowed-headers=Authorization,Content-Type
app.cors.exposed-headers=Authorization
app.cors.allow-credentials=true
app.cors.max-age=3600
 
# KAFKA COMMON CONFIG
 
spring.kafka.bootstrap-servers=192.168.0.245:9092

 
# CONSUMER CONFIG
 
#spring.kafka.consumer.group-id=pricing-group
spring.kafka.consumer.group-id=test-group-10
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.spacezant.pricing.dto.product.ProductCreatedEvent

# Trust all packages (important for DTO)
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Optional: show type info correctly
spring.kafka.consumer.properties.spring.json.use.type.headers=false

 
# PRODUCER CONFIG
 
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

 
# OPTIONAL (DEBUGGING)
 
spring.kafka.listener.missing-topics-fatal=false
logging.level.org.springframework.kafka=DEBUG